jobs:
  - name: runsh-job-pvt
    type: runSh
    allowPublicAccess: false
    steps:
      - IN: sample-scriptpvtgitreporepo
      - IN: tr_11
     # - IN: trigger01
    #  - IN: test-trigger01
      - TASK:
        - script: IN/sample-scriptpvtgitreporepo/gitRepo/echo.sh
    flags: job1
    
  - name: runcliscript-job-pvt
    type: runCLI
    allowPublicAccess: true
    steps:      
      - IN: sample-scriptpvtgitreporepo
      - TASK:
        - script: IN/sample-scriptpvtgitreporepo/gitRepo/echo.sh
    flags: job-runcli
  
  - name: sample_privaterepo_runCI
    type: runCI
    steps:
      - IN: sample_privaterepo_ciRepo
     # - IN: runcli-jobrunCI-pvt
      - IN: tr_2
  
 # - name: runcli-jobrunCI-pvt
  #  type: runCLI
  #  allowPublicAccess: true
  #  steps:      
  #    - IN: sample-scriptpvtgitreporepo
   #   - TASK:
    #    - script: ls
        
  - name: runsh-jobrunCI-pvt
    type: runSh
    steps:
      - IN: sample_privaterepo_runCI
      - IN: tr_3
      - TASK:
        - script: ls
        
  - name: manifest_dep_pvt
    type: manifest
    steps:
      - IN: sample_img_pvt  
    flags: manifest
  
  - name: deploy_ddc_pvt
    type: deploy
    steps:      
      - IN: manifest_dep_pvt
      - IN: ddc-clusterpvt
    flags: deploy_ddc
    
  - name: runsh-job2-pvt
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: runsh-job-pvt
     # - IN: trigger01
    #  - IN: test-trigger01
      - TASK:
        - script: ls

  - name: runcliscript-job2-pvt
    type: runCLI
    steps:      
      - IN: runcliscript-job-pvt
      - TASK:
        - script: ls
 
  #- name: sample_privaterepo_runCI
   # type: runCI
   # allowPublicAccess: true
   # steps:
   #   - IN: sample_privaterepo_ciRepo
   # flags:
   #   - sample_privaterepo_runCI
   #   - sample_privaterepo_runCIEnabledFromCIbutAddedFlagsInJobsYml      
      
  - name: sample-release-pvt
    type: release
    allowPublicAccess: true
    steps:
      - IN: sample-version-pvt
      - TASK: managed
        bump: rc
        
  - name: sample-ddcdeploy-pvt
    type: deploy
    allowPublicAccess: true
    steps:
      - IN: sample-ddccluster-pvt
      - IN: manifest_dep_pvt
      - IN: sample-params-pvt
      - IN: sample-dopts-pvt
      - IN: tr_5
      - IN: tr_6
    on_success:
      - NOTIFY: sample-email-pvt
      - NOTIFY: sample-slack-pvt
      
  - name: sample-provision-pvt                                            
    type: provision     
    allowPublicAccess: true
    steps:
      - IN: sample-files-pvt
      
  #- name: sample-jenkins-pvt                  # a memorable, unique name. this is how your job will be referred to in shippable pipelines
   # type: jenkinsJob # The type of the job (should not be changed by the user)
    #allowPublicAccess: true
    #integration: "jenkins"   # The name of your Jenkins integration (created via accountSettings page)
    #pointer:
     # sourceName: "firstjob"          # The name of your Jenkins job
    #steps:
     # - OUT: "sample-files-pvt"
      